<a href="https://colab.research.google.com/github/chengpeter88/python40001/blob/main/HW3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Q1
n = int(input())
print("*****")
print(" ****")
print("  ***")
print("   **")
print("    *")

n = int(input())
for i in range(1,n+1,1):
  for j in range(1,n-i,1):
    print("*",end=" ")
  print()


for i in range(1,6,1):
  for j in range(1,6-i,1):
    print("*",end=" ")
  print()
#第一列 五個
#第二列 4個 一個 空白

5
*****
 ****
  ***
   **
    *
5
* * * 
* * 
* 


* * * * 
* * * 
* * 
* 



In [ ]:
#Q2
n=int(input())
for i in range(n):
  for j in range(n-i-1):
    print(" ",end="")
  for k in range(i+1):
    print("*",end="")
  print()

5
    *
   **
  ***
 ****
*****


In [ ]:
#Q3
#function


point1=[]
point2=[]
x1=int(input())
y1=int(input())
x2=int(input())
y2=int(input())
point1.append(x1)
point1.append(y1)
point2.append(x2)
point2.append(y2)
#print(point1)
#print(point2)
def get_dist(point1,pont2):
  for i in point1[0]:

34
[34]


NameError: ignored

In [ ]:
#Q4
import random
import numpy  as np
row=int(input())
col=int(input())
a=np.zeros((5, 3),dtype=np.int32)
for i in range(row):
  for j in range(col):
    a[i,j]=random.randint(1,20)
print(a)


5
3
[[ 3 14 11]
 [15  7 17]
 [16 15 13]
 [20 12  8]
 [18 11  2]]
