<a href="https://colab.research.google.com/github/chengpeter88/python40001/blob/main/hw4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Q1
import numpy as np
A=np.zeros((2,3))
B=np.zeros((3,2))

print("A:")
for i in range(2):
  A[i,:] = np.array(list(map(lambda x: int(x), input().split())))
print("B:")
for i in range(3):
  B[i,:] = np.array(list(map(lambda x: int(x), input().split())))

print(A)
print(B)

ans=np.matmul(A,B)
print(ans)

A:
2 3 5
5 7 8
B:
1 2
3 10
2 6
[[2. 3. 5.]
 [5. 7. 8.]]
[[ 1.  2.]
 [ 3. 10.]
 [ 2.  6.]]
[[ 21.  64.]
 [ 42. 128.]]


In [ ]:
class_a=np.array([32,57,89,82,98,57,88,56,93,91])
class_b=np.array([88,93,20,70,56,83,92,100,80,97])
class_c=np.array([82,75,83,95,96,90,77,82,90,88])
print("A class總和為:",np.sum(class_a,axis=0),"最大:",np.max(class_a,axis=0))
print("B class總和為:",np.sum(class_b,axis=0),"最大:",np.max(class_b,axis=0))
print("C class總和為:",np.sum(class_c,axis=0),"最大:",np.max(class_c,axis=0))

A class總和為: 743 最大: 98
B class總和為: 779 最大: 100
C class總和為: 858 最大: 96
